name: Redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - core-1
    paths:
      - 'docs/**'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy
        env:
          WEBSITE_DEPLOY_HOOK: ${{ secrets.WEBSITE_DEPLOY_HOOK }}
        run: |
          curl -X POST $WEBSITE_DEPLOY_HOOK
      - name: Trigger search reindex
        env:
          SEARCH_INDEX_DEPLOY_HOOK: ${{ secrets.SEARCH_INDEX_DEPLOY_HOOK }}
        run: |
          curl -X POST $SEARCH_INDEX_DEPLOY_HOOK
